# Generated by Django 4.2.1 on 2023-07-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_userfollows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(
                blank=True, max_length=8192, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="headline",
            field=models.CharField(max_length=128, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (0, "- 0"),
                    (1, "- 1"),
                    (2, "- 2"),
                    (3, "- 3"),
                    (4, "- 4"),
                    (5, "- 5"),
                ],
                verbose_name="Note",
            ),
        ),
    ]
